import { useEffect, useMemo, useState } from "react";
import { Activity, AlertTriangle, Bell, Bot, CheckCircle2, ChevronDown, ChevronRight, CircleGauge, Cpu, Droplets, Gauge, Layers3, Menu, Network, Play, Power, Radio, Search, Settings2, ShieldCheck, SlidersHorizontal, Sparkles, Thermometer, TowerControl, TriangleAlert, Waves, X, Zap } from "lucide-react";

type Detail = { title: string; eyebrow: string; value: string; description: string; rows: Array<[string, string]> };

const navItems = ["Overview", "Digital Twin", "Live Sensors", "Leak Detection", "AI Insights", "Alerts", "Predictions", "Reports"];
const navIcons = [Layers3, Network, Radio, TriangleAlert, Bot, Bell, CircleGauge, SlidersHorizontal];
const details: Record<string, Detail> = {
  "LIVE FLOW": { title: "Live flow diagnostics", eyebrow: "FLOW SENSOR NETWORK", value: "1,248 L/min", description: "Current production demand is within the expected operating envelope. The intelligence engine is comparing live flow against pressure, shift timing, and historical baselines.", rows: [["Previous 10 min", "1,232 L/min"], ["Average flow", "1,184 L/min"], ["Peak flow", "1,306 L/min"], ["Flow velocity", "2.4 m/s"], ["Sensor ID", "FLW-042-A"], ["Anomaly status", "Normal"]] },
  "WATER CONSUMPTION": { title: "Consumption intelligence", eyebrow: "PRODUCTION WATER USE", value: "18,420 L today", description: "Consumption is tracking 6.4% below the expected production-adjusted baseline, preventing unnecessary waste across the network.", rows: [["Expected baseline", "19,680 L"], ["Variance", "−1,260 L"], ["Peak shift", "Shift B"], ["Largest draw", "Line B cooling"], ["Forecast EOD", "24,860 L"], ["Confidence", "97.2%"]] },
  "WATER LOSS DETECTED": { title: "Loss event analysis", eyebrow: "LEAK DETECTION ENGINE", value: "326 L detected", description: "A pressure-flow mismatch was detected downstream of Pump P-02. The engine classifies this as a probable leak, not normal production variation.", rows: [["Leak probability", "87%"], ["Estimated rate", "18.2 L/min"], ["Likely zone", "Pipeline C-07"], ["First detected", "09:58:42"], ["Water at risk / hr", "1,092 L"], ["Recommended action", "Inspect valve V-12"]] },
  "SYSTEM HEALTH": { title: "System health overview", eyebrow: "NETWORK RELIABILITY", value: "94% healthy", description: "The network is online and reporting. Two pressure sensors need inspection, while critical flow paths remain available.", rows: [["Sensors online", "116 / 120"], ["Pumps available", "3 / 3"], ["Critical alerts", "1"], ["Warning alerts", "3"], ["Last maintenance", "Today, 07:42"], ["Uptime / 30 days", "99.1%"]] },
  "FINANCIAL LOSS": { title: "Financial impact detail", eyebrow: "LOSS INTELLIGENCE", value: "₹845 total", description: "Estimated financial impact combines direct water tariff, treatment cost, and pumping energy cost for the current loss event.", rows: [["Direct water cost", "₹640"], ["Treatment cost", "₹120"], ["Pumping / energy", "₹85"], ["Projected daily loss", "₹20,280"], ["Projected monthly loss", "₹6.08 lakh"], ["Projection status", "Simulation"]] },
  "LEAK RISK": { title: "Leak risk detail", eyebrow: "PREDICTIVE ALERT ENGINE", value: "87% probability", description: "Pressure drift, flow variance, and sensor agreement point to a probable leak in Pipeline Segment P-03 → P-04.", rows: [["Current risk", "87%"], ["Risk in 6 hours", "94%"], ["Root-cause confidence", "86%"], ["Sensor confidence", "91%"], ["Physical zone", "Zone B / Block 2"], ["Recommended action", "Inspect P-04"]] },
};

const kpis = [
  { label: "LIVE FLOW", value: "1,248", unit: "L/min", trend: "+5.2%", tone: "cyan", icon: Waves },
  { label: "WATER CONSUMPTION", value: "18,420", unit: "L today", trend: "−6.4%", tone: "blue", icon: Droplets },
  { label: "WATER LOSS DETECTED", value: "326", unit: "L", trend: "87% probability", tone: "red", icon: TriangleAlert },
  { label: "FINANCIAL LOSS", value: "₹845", unit: "estimated", trend: "₹20,280 / day", tone: "amber", icon: CircleGauge },
  { label: "LEAK RISK", value: "87", unit: "%", trend: "P-03 → P-04", tone: "red", icon: AlertTriangle },
  { label: "SYSTEM HEALTH", value: "94", unit: "%", trend: "116 / 120 online", tone: "green", icon: ShieldCheck },
];

function FlowPath({ active = false }: { active?: boolean }) { return <path className={active ? "flow-line active" : "flow-line"} d="M45 145 H200 C225 145 228 105 258 105 H394 C420 105 426 145 454 145 H540" />; }
function SensorNode({ x, y, tone, label, onClick }: { x: number; y: number; tone: string; label: string; onClick: () => void }) { return <button className={`sensor-node ${tone}`} style={{ left: `${x}%`, top: `${y}%` }} onClick={onClick} title={label}><span /><small>{label}</small></button>; }

export default function Home() {
  const [activeNav, setActiveNav] = useState("Overview");
  const [selected, setSelected] = useState<Detail | null>(null);
  const [demoMode, setDemoMode] = useState(true);
  const [mobileOpen, setMobileOpen] = useState(false);
  const [tick, setTick] = useState(42);
  const [toast, setToast] = useState("");
  const [judgeMode, setJudgeMode] = useState(false);
  const [leakRate, setLeakRate] = useState(20);
  const [duration, setDuration] = useState(8);
  useEffect(() => { const id = window.setInterval(() => setTick((value) => value + 1), 2400); return () => window.clearInterval(id); }, []);
  useEffect(() => { if (!toast) return; const id = window.setTimeout(() => setToast(""), 2600); return () => window.clearTimeout(id); }, [toast]);
  const liveFlow = useMemo(() => (1248 + (tick % 7) * 3).toLocaleString(), [tick]);
  const simulatedLoss = leakRate * duration * 60;
  const simulatedImpact = Math.round(simulatedLoss * 0.08 + simulatedLoss * 0.015 + simulatedLoss * 0.011);
  const action = (message: string) => setToast(message);
  const selectEquipment = (kind: "pipe" | "tank" | "pump") => {
    const map: Record<string, Detail> = {
      pipe: { title: "Pipeline C-07 diagnostics", eyebrow: "DIGITAL TWIN / PIPE SEGMENT", value: "87% leak probability", description: "The flow difference is outside the production-adjusted baseline. Pressure decay and persistent nighttime flow suggest a downstream leak.", rows: [["Pipe ID", "C-07 / East loop"], ["Flow rate", "428 L/min"], ["Expected flow", "446 L/min"], ["Actual flow", "428 L/min"], ["Flow difference", "−18 L/min"], ["Last maintenance", "12 Aug 2026"]] },
      tank: { title: "Storage tank T-01", eyebrow: "DIGITAL TWIN / STORAGE", value: "72% capacity", description: "Tank level is stable. Inflow is currently higher than outflow and the predicted empty time remains outside the risk window.", rows: [["Tank level", "72% / 50,000 L"], ["Inflow", "580 L/min"], ["Outflow", "522 L/min"], ["Capacity", "50,000 L"], ["Predicted empty time", "18h 42m"], ["Level trend", "Stable"]] },
      pump: { title: "Pump P-02 performance", eyebrow: "DIGITAL TWIN / PUMP", value: "Running · 1,480 RPM", description: "Pump output is available and within the normal operating range. Temperature is elevated but not yet at the maintenance threshold.", rows: [["Pump status", "Running"], ["Pressure", "4.8 bar"], ["Flow", "428 L/min"], ["Energy usage", "18.4 kW"], ["Temperature", "62°C"], ["Maintenance", "Due in 18 days"]] },
    };
    setSelected(map[kind]);
  };
  return <div className="hydro-app">
    <aside className={`hydro-sidebar ${mobileOpen ? "open" : ""}`}>
      <div className="hydro-brand"><div className="hydro-logo"><Droplets size={19} /></div><div><strong>HYDRO<span>SENSE</span></strong><small>INDUSTRIAL WATER INTELLIGENCE</small></div><button className="mobile-close" onClick={() => setMobileOpen(false)}><X size={18} /></button></div>
      <div className="plant-select"><div className="plant-symbol"><TowerControl size={17} /></div><div><small>ACTIVE FACILITY</small><strong>Plant 04 · Northstar</strong></div><ChevronDown size={14} /></div>
      <div className="hydro-nav-label">COMMAND CENTER</div><nav>{navItems.map((item, index) => { const Icon = navIcons[index]; return <button key={item} className={activeNav === item ? "active" : ""} onClick={() => { setActiveNav(item); setMobileOpen(false); }}><Icon size={16} /><span>{item}</span>{item === "Alerts" && <b>04</b>}</button>; })}</nav>
      <div className="sidebar-bottom"><button className="simulator-card" onClick={() => setDemoMode(!demoMode)}><div className="simulator-icon"><Cpu size={16} /></div><div><small>HARDWARE SIMULATOR</small><strong>{demoMode ? "CONNECTED" : "PAUSED"}</strong></div><span className={demoMode ? "connected-dot" : "paused-dot"} /></button><button className="sidebar-settings" onClick={() => action("System settings opened.")}><Settings2 size={16} /> System settings</button></div>
    </aside>
    {mobileOpen && <button className="hydro-scrim" onClick={() => setMobileOpen(false)} />}
    <main className="hydro-main">
      <header className="hydro-topbar"><button className="mobile-menu" onClick={() => setMobileOpen(true)}><Menu size={19} /></button><div className="top-crumb"><span>COMMAND CENTER</span><ChevronRight size={13} /><strong>{activeNav.toUpperCase()}</strong></div><div className="top-status"><span className="online-chip"><i /> SYSTEM STATUS: ONLINE</span><span className="live-chip"><i /> LAST UPDATED: LIVE</span><button className="top-icon" onClick={() => action("No new critical notifications.")}><Bell size={17} /><b>4</b></button><button className="operator-avatar" onClick={() => action("Operator profile opened.")}>OP</button></div></header>
      <div className="hydro-content">
        <section className="hydro-hero"><div><p className="overline"><span /> DIGITAL TWIN / REAL-TIME MONITORING</p><h1>Industrial Water <em>Intelligence</em></h1><p className="hero-copy">Real-time monitoring, anomaly detection and predictive leak prevention.</p></div><div className="hero-actions"><span className="demo-toggle-label">DEMO MODE</span><button className={`demo-toggle ${demoMode ? "on" : ""}`} onClick={() => setDemoMode(!demoMode)}><span /></button><button className="run-button" onClick={() => action("Intelligence scan complete — network baseline is current.")}><Play size={14} fill="currentColor" /> Run intelligence scan</button></div></section>
        <section className="kpi-grid">{kpis.map((kpi) => { const Icon = kpi.icon; return <button className={`hydro-kpi ${kpi.tone}`} key={kpi.label} onClick={() => setSelected(details[kpi.label])}><div className="kpi-head"><span>{kpi.label}</span><Icon size={17} /></div><strong>{kpi.label === "LIVE FLOW" ? liveFlow : kpi.value}<small>{kpi.unit}</small></strong><div className="kpi-foot"><span>{kpi.trend}</span><em>{kpi.label === "WATER LOSS DETECTED" ? "critical zone" : kpi.label === "FINANCIAL LOSS" ? "loss intelligence" : kpi.label === "LEAK RISK" ? "predicted risk" : "vs. expected baseline"}</em></div><div className="kpi-spark"><span /><span /><span /><span /><span /><span /></div><i className="tap-detail">OPEN DIAGNOSTICS <ChevronRight size={11} /></i></button>; })}</section>
        <section className="command-grid"><article className="twin-panel hydro-panel"><div className="panel-head"><div><p className="panel-overline">LIVE DIGITAL TWIN</p><h2>Industrial water network <span className="streaming"><i /> STREAMING</span></h2></div><button className="panel-action" onClick={() => action("Digital twin expanded to full network view.")}>Expand view <Layers3 size={14} /></button></div><div className="twin-canvas"><div className="twin-grid" /><div className="twin-caption source">WATER SOURCE</div><div className="twin-equipment source-node"><Droplets size={20} /><strong>Source</strong><small>Municipal feed</small></div><div className="twin-equipment tank-node" onClick={() => selectEquipment("tank")}><div className="tank-liquid" /><div className="tank-top" /><strong>Tank T-01</strong><small>72% level</small></div><div className="twin-equipment pump-node" onClick={() => selectEquipment("pump")}><Power size={18} /><strong>Pump P-02</strong><small>1,480 RPM</small></div><div className="line-label main-label">MAIN PIPELINE · A-01</div><div className="line-label c-label">PIPELINE C-07 · LEAK RISK</div><div className="production-label">PRODUCTION LINES</div><div className="production-node line-a"><span />Line A <small>Normal</small></div><div className="production-node line-b"><span />Line B <small>Normal</small></div><div className="production-node line-c"><span />Line C <small>Warning</small></div><svg className="twin-svg" viewBox="0 0 900 420" preserveAspectRatio="none"><FlowPath active /><path className="pipe-branch" d="M394 105 V220 H610 M394 105 V300 H610 M610 220 H790 M610 300 H790" /><path className="pipe-branch" d="M258 105 V330 H145" /><circle className="pipe-dot" cx="394" cy="105" r="6" /><circle className="pipe-dot warning" cx="610" cy="300" r="6" /><circle className="pipe-dot critical" cx="610" cy="220" r="6" /></svg><SensorNode x={38} y={26} tone="normal" label="P-01" onClick={() => action("P-01: 4.1 bar · normal")} /><SensorNode x={53} y={24} tone="normal" label="FLW-042" onClick={() => setSelected(details["LIVE FLOW"])} /><SensorNode x={68} y={51} tone="critical" label="LEAK" onClick={() => selectEquipment("pipe")} /><SensorNode x={68} y={70} tone="warning" label="PRS-18" onClick={() => action("PRS-18: pressure variance detected.")} /><button className="twin-alert" onClick={() => setSelected(details["WATER LOSS DETECTED"])}><TriangleAlert size={14} /><span><strong>Probable leak detected</strong><small>Pipeline C-07 · 87% confidence</small></span><ChevronRight size={15} /></button></div><div className="twin-legend"><span><i className="normal" />Normal</span><span><i className="warning" />Warning</span><span><i className="critical" />Critical</span><span className="legend-hint"><Zap size={12} /> Click a sensor, pipe, tank, or pump for diagnostics</span></div></article>
          <aside className="insight-column"><article className="hydro-panel ai-panel"><div className="panel-head"><div><p className="panel-overline">AI INTELLIGENCE ENGINE</p><h2>What the system sees</h2></div><div className="ai-icon"><Sparkles size={15} /></div></div><div className="ai-status"><span className="pulse-ring"><Bot size={19} /></span><div><strong>Anomaly classification active</strong><small>Comparing production context + sensor history</small></div></div><div className="classification"><div><span>Normal variation</span><strong>72%</strong><i><b style={{ width: "72%" }} /></i></div><div><span>Possible leak</span><strong className="red-text">87%</strong><i><b className="red-bar" style={{ width: "87%" }} /></i></div><div><span>Sensor anomaly</span><strong>14%</strong><i><b className="amber-bar" style={{ width: "14%" }} /></i></div></div><div className="ai-explanation"><AlertTriangle size={15} /><p><strong>Why this matters</strong> Flow is 18 L/min below expected while pressure is decaying downstream. Pattern persists outside production hours.</p></div><button className="insight-button" onClick={() => setSelected(details["WATER LOSS DETECTED"])}>View AI explanation <ChevronRight size={14} /></button></article><article className="hydro-panel alerts-panel"><div className="panel-head"><div><p className="panel-overline">ALERT QUEUE</p><h2>Active alerts <span className="alert-count">04</span></h2></div><button className="panel-action" onClick={() => setActiveNav("Alerts")}>View all</button></div><div className="alert-row critical-row" onClick={() => setSelected(details["WATER LOSS DETECTED"])}><div className="alert-icon"><TriangleAlert size={15} /></div><div><strong>Probable leak detected</strong><small>C-07 · 8 min ago</small></div><span>CRITICAL</span></div><div className="alert-row warning-row" onClick={() => action("Pressure variance details opened.")}><div className="alert-icon"><Activity size={15} /></div><div><strong>Pressure variance</strong><small>PRS-18 · 21 min ago</small></div><span>WARNING</span></div><div className="alert-row info-row"><div className="alert-icon"><Thermometer size={15} /></div><div><strong>Pump temperature elevated</strong><small>P-02 · 34 min ago</small></div><span>INFO</span></div></article></aside></section>
        <section className="intel-grid"><article className="hydro-panel loss-panel"><div className="panel-head"><div><p className="panel-overline">LOSS INTELLIGENCE</p><h2>Water loss → money loss</h2></div><button className="panel-action" onClick={() => action("Loss breakdown refreshed from simulation inputs.")}>Show breakdown <ChevronRight size={14} /></button></div><div className="loss-flow"><div><small>WATER LOST</small><strong>8,000 L</strong></div><ChevronRight size={15} /><div><small>TOTAL ESTIMATED LOSS</small><strong className="amber-value">₹845</strong></div></div><div className="loss-rows"><span>Direct water cost <b>₹640</b></span><span>Treatment cost <b>₹120</b></span><span>Pumping / energy <b>₹85</b></span><span>Projected annualized loss <b>₹73 lakh</b></span></div></article><article className="hydro-panel prediction-panel"><div className="panel-head"><div><p className="panel-overline">PREDICTIVE ALERT ENGINE</p><h2>Early anomaly predicted</h2></div><span className="early-badge">LEVEL 1 · PREDICT</span></div><div className="prediction-core"><div><strong>72%</strong><small>risk in next 6 hours</small></div><div className="prediction-reason"><span>Pipeline P-04</span><p>Pressure has decreased <b>8%</b> while flow variance increased <b>12%</b>.</p></div></div><button className="insight-button" onClick={() => action("Maintenance recommendation scheduled for P-04.")}>Inspect P-04 during next maintenance window <ChevronRight size={14} /></button></article><article className="hydro-panel balance-panel"><div className="panel-head"><div><p className="panel-overline">WATER BALANCE ENGINE</p><h2>Mass balance</h2></div><Network size={17} className="panel-muted-icon" /></div><div className="balance-equation"><span>50,000 L <small>input</small></span><b>−</b><span>39,000 L <small>process</small></span><b>−</b><span>1,000 L <small>known loss</small></span><b>=</b><strong>10,000 L <small>unaccounted</small></strong></div><p className="balance-note"><AlertTriangle size={14} /> Possible causes: pipeline leakage · valve failure · meter error</p></article></section>
        <section className="lab-grid"><article className="hydro-panel lab-panel"><div className="panel-head"><div><p className="panel-overline">WATER LOSS LAB · SIMULATION MODE</p><h2>What happens if we do nothing?</h2></div><span className="sim-badge">SIMULATION</span></div><div className="slider-row"><label>Leak rate <b>{leakRate} L/min</b></label><input type="range" min="5" max="80" value={leakRate} onChange={(event) => setLeakRate(Number(event.target.value))} /></div><div className="slider-row"><label>Duration <b>{duration} hours</b></label><input type="range" min="1" max="24" value={duration} onChange={(event) => setDuration(Number(event.target.value))} /></div><div className="lab-result"><div><small>PROJECTED WATER LOSS</small><strong>{simulatedLoss.toLocaleString()} L</strong></div><div><small>FINANCIAL IMPACT</small><strong>₹{simulatedImpact.toLocaleString()}</strong></div><div><small>IF IGNORED</small><strong className="red-text">{duration >= 12 ? "CRITICAL" : "ESCALATING"}</strong></div></div></article><article className="hydro-panel timeline-panel"><div className="panel-head"><div><p className="panel-overline">INCIDENT REPLAY</p><h2>AI event timeline</h2></div><button className="panel-action" onClick={() => setJudgeMode(!judgeMode)}>{judgeMode ? "Pause replay" : "Replay incident"} <Play size={12} /></button></div><div className="event-timeline"><span><b>14:28</b><em>Pressure deviation detected</em></span><span><b>14:29</b><em>Flow imbalance detected</em></span><span className="active-event"><b>14:32</b><em>Leak localized to P-04</em></span><span><b>14:32</b><em>Critical alert generated</em></span></div></article><article className="hydro-panel decision-panel"><div className="panel-head"><div><p className="panel-overline">HUMAN-IN-THE-LOOP</p><h2>Operator decision</h2></div><ShieldCheck size={17} className="panel-muted-icon" /></div><p className="decision-copy">AI recommends: <strong>Inspect P-04 within 30 minutes.</strong></p><div className="decision-buttons"><button onClick={() => action("Recommendation accepted and recorded.")}>Accept</button><button onClick={() => action("Incident moved to monitoring.")}>Monitor</button><button onClick={() => action("Escalation sent to maintenance.")}>Escalate</button></div></article></section>
        <section className="bottom-strip"><div><span className="strip-icon"><Network size={16} /></span><div><small>PREDICTED LOSS · NEXT 24H</small><strong>2,184 L <em>if no action is taken</em></strong></div></div><div><span className="strip-icon amber"><Gauge size={16} /></span><div><small>RECOMMENDED ACTION</small><strong>Inspect valve V-12 <em>confidence 91%</em></strong></div></div><div><span className="strip-icon green"><CheckCircle2 size={16} /></span><div><small>NETWORK AVAILABILITY</small><strong>99.1% <em>all critical paths active</em></strong></div></div></section>
        <footer className="hydro-footer"><span><i /> Hydrosense intelligence stream active · Simulator {demoMode ? "connected" : "paused"}</span><span>Last model refresh 10:42:18 · v3.8.2</span></footer>
      </div>
    </main>
    {selected && <div className="hydro-overlay" onClick={() => setSelected(null)}><section className="hydro-drawer" onClick={(event) => event.stopPropagation()}><div className="drawer-head"><div><p className="panel-overline">{selected.eyebrow}</p><h2>{selected.title}</h2></div><button className="top-icon" onClick={() => setSelected(null)}><X size={17} /></button></div><div className="drawer-value"><strong>{selected.value}</strong><span>{selected.description}</span></div><div className="drawer-rows">{selected.rows.map(([label, value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><button className="run-button full" onClick={() => { setSelected(null); action("Diagnostic action logged for operator review."); }}><ShieldCheck size={14} /> Acknowledge diagnostics</button></section></div>}
    {toast && <div className="hydro-toast"><CheckCircle2 size={15} /><span>{toast}</span><button onClick={() => setToast("")}><X size={13} /></button></div>}
  </div>;
}
